[workspace]
resolver = "2"
members = [
  "crates/alembic-core",
  "crates/alembic-engine",
  "crates/alembic-adapter-registry",
  "crates/alembic-adapter-netbox",
  "crates/alembic-adapter-nautobot",
  "crates/alembic-adapter-infrahub",
  "crates/alembic-cli",
  "crates/alembic-adapter-generic",
  "crates/alembic-adapter-peeringdb",
  "crates/alembic-django",
]

[workspace.package]
edition = "2021"
rust-version = "1.95"
license = "Apache-2.0"
repository = "https://github.com/cyberwitchery/alembic"
homepage = "https://github.com/cyberwitchery/alembic"

[workspace.dependencies]
alembic-core = { version = "0.2.0", path = "crates/alembic-core" }
alembic-engine = { version = "0.2.0", path = "crates/alembic-engine" }
alembic-adapter-registry = { version = "0.2.0", path = "crates/alembic-adapter-registry" }
alembic-adapter-netbox = { version = "0.2.0", path = "crates/alembic-adapter-netbox" }
alembic-adapter-nautobot = { version = "0.2.0", path = "crates/alembic-adapter-nautobot" }
alembic-adapter-infrahub = { version = "0.2.0", path = "crates/alembic-adapter-infrahub" }
alembic-adapter-generic = { version = "0.2.0", path = "crates/alembic-adapter-generic" }
alembic-adapter-peeringdb = { version = "0.2.0", path = "crates/alembic-adapter-peeringdb" }
alembic-django = { version = "0.2.0", path = "crates/alembic-django" }
anyhow = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = { package = "serde_yaml_ng", version = "0.10" }
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1", features = ["serde", "v4", "v5"] }
netbox = "0.3.3"
nautobot = "0.3.1"
infrahub = "0.1.0"
reqwest = { version = "0.12", features = ["json"] }
regex = "1"
ipnet = "2"
tokio-postgres = "0.7"
native-tls = "0.2"
postgres-native-tls = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
httpmock = "0.7"
tempfile = "3"
futures = "0.3"
semver = "1"
escargot = "0.5"
figment = { version = "0.10", features = ["toml", "env"] }