[package]
name = "alembic-django"
version = "0.1.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/alembic-django"
description = "Django app scaffolding for Alembic."
readme = "../../README.md"

[dependencies]
alembic-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = { workspace = true }
uuid.workspace = true
