[package]
name = "alembic-cli"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/alembic-cli"
description = "Command line interface for Alembic."
readme = "../../README.md"

[dependencies]
alembic-core.workspace = true
alembic-engine.workspace = true
alembic-adapter-registry.workspace = true
alembic-django.workspace = true
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
figment.workspace = true
serde.workspace = true

[dev-dependencies]
httpmock = { workspace = true }
tempfile = { workspace = true }
uuid.workspace = true
