[package]
name = "alembic-cli"
version = "0.1.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/alembic-cli"
description = "Command line interface for Alembic."
readme = "../../README.md"

[dependencies]
alembic-core.workspace = true
alembic-engine.workspace = true
alembic-adapter-registry.workspace = true
alembic-django.workspace = true
alembic-adapter-containerlab.workspace = true
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
httpmock = "0.7"
tempfile = "3"
uuid.workspace = true
