[package]
name = "alembic-file-generator"
version = "0.8.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "A tool for generating alembic files (for testing)."
readme = "../../README.md"
# an internal generator for scale testing, not part of the release
publish = false

[dependencies]
alembic-core.workspace = true
alembic-engine.workspace = true
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
tempfile.workspace = true
