[package]
name = "alembic-adapter-nautobot"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/alembic-adapter-nautobot"
description = "Nautobot adapter for Alembic."
readme = "../../README.md"

[dependencies]
alembic-core = { path = "../alembic-core" }
alembic-engine = { path = "../alembic-engine" }
anyhow = { workspace = true }
async-trait = { workspace = true }
nautobot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
futures = "0.3"
tracing = { workspace = true }

[dev-dependencies]
httpmock = "0.7"
tempfile = "3"
