[package]
name = "alembic-adapter-generic"
version = "0.1.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/alembic-adapter-generic"
description = "Generic REST adapter for Alembic."
readme = "../../README.md"

[dependencies]
alembic-core.workspace = true
alembic-engine.workspace = true
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
futures = "0.3"

[dev-dependencies]
httpmock = "0.7"
