[package]
name = "alembic-adapter-infrahub"
version = "0.1.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/alembic-adapter-infrahub"
description = "Infrahub GraphQL adapter for Alembic."
readme = "../../README.md"

[dependencies]
alembic-core.workspace = true
alembic-engine.workspace = true
anyhow.workspace = true
async-trait.workspace = true
infrahub.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tracing.workspace = true
reqwest.workspace = true
graphql-parser = "0.4"
tokio = { workspace = true, features = ["process"] }

[dev-dependencies]
httpmock = "0.7"
